spring:
  datasource:
    url: jdbc:mysql://localhost:3308/faTest
    #url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/faTest
    username: root
    password: sql1
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always
  jpa:
    show-sql: true  # Enable SQL logging
  

# Other Spring Boot configurations
server:
  port: 7417
  


#mysql -h 127.0.0.1 -u root -psql123



#I assume that you already have a mysql image
#docker run --name springtestdatabase --network mynetwork  -e MYSQL_ROOT_PASSWORD=sql1 -e MYSQL_USER=sql1 -e MYSQL_PASSWORD=sql1 -p 3307:3306 -d mysql

#docker run --name springtestdatabase  -e MYSQL_ROOT_PASSWORD=sql1 -e MYSQL_USER=sql1 -e MYSQL_PASSWORD=sql1 -p 3307:3306 -d mysql

#docker run -p 3307:3306 --name springtestdatabase -e MYSQL_ROOT_PASSWORD=sql1  -e MYSQL_DATABASE=faTest mysql


#enter database 
#docker exec -it springtestdatabase  /bin/bash

#execute that to check mysql 
#docker exec -it springtestdatabase mysql -u sql1 -psql1    (for sql1 user )
#docker exec -it springtestdatabase    mysql -u root -psql1   (for root user)
#docker exec -it springtestdatabase mysql -u root -psql1 -h 172.21.0.2 (if it is a network - get the ip4 address from docker inspect network)

#create database faTest;



#docker run -d -p 7417:7417 --network mynetrowk springtest

